### ISSUE TITLE
Things not working as smoothly as expected - possible user error

### ISSUE THREAD

**Issue by milesfrain** [sriharshachilakapati/vimmer-ps#5]
Are the issues noted in this post (see last section) expected, or do I have something misconfigured?

https://discourse.purescript.org/t/vim-ide-options/1477

**Comment by sriharshachilakapati** [comment]
I'll try to answer by quoting the points in that link here:

> I can’t figure out how to fill an autocomplete suggestion presented by deoplete. The popup works, and I can cycle between all the suggestions, but I don’t know what key to press to insert the suggested text.

The default key to accept an autocomplete suggestion is Ctrl+Y.

> Jump to definition doesn’t work for library functions. For example with cursor on the `const` symbol running `:call LanguageClient#textDocument_definition()` or using the mapped binding `\g` doesn’t take me to the definition in prelude. It just says “[LC] Not found!”.

There can be 2 reasons for this behaviour. I noticed that for some reason, the modules aren't being completely loaded on the first run. Use `:Pbuild` command to load all the symbols. Default binding is `\l` for that.

Second reason, the one affecting you for not being able to go to the definition of library modules might be how your project is setup. This plugin currently only supports `bower` and `psc-package` based projects only. We still haven't started using Spago yet. Will have to add support for them.

> The documentation popup is missing lots of valuable info.

I'm not sure regarding this one. This one is implemented in the `LanguageClient_NeoVim` plugin itself, and it displays whatever the language server returns to you. Maybe we can find something if you can elaborate more.

**Comment by milesfrain** [comment]
> The default key to accept an autocomplete suggestion is Ctrl+Y.

Thanks for clarifying. I wish this note was part of the deoplete docs (even though this seems to be a built-in feature of vim) . Also just discovered that Ctrl+n or Ctrl+p fills-in the text so you can skip Ctrl+y to select. Using arrow keys requires Ctrl+y to populate the text.

> Use `:Pbuild` command to load all the symbols.

I'm getting a "[LC] [Error] Problem running build: didn't find JSON output" when I attempt to do that. I assume this is due to it being a `spago` project.

> Maybe we can find something if you can elaborate more.

I was hoping it would return the same info as the [pursuit entry](https://pursuit.purescript.org/packages/purescript-prelude/4.1.1/docs/Data.Function#v:const). This is what happens in vscode, and CoC tries to do this (although formatting is messed-up). Understandable if this requires more digging into LanguageClient_NeoVim.

**Comment by sriharshachilakapati** [comment]
@milesfrain I've added psc-package & Spago support in v0.1.4, please try once again.
