### ISSUE TITLE
Language server crashes constantly

### ISSUE THREAD

**Issue by carbolymer** [sriharshachilakapati/vimmer-ps#6]
I've configured my vim using LanguageClient-neovim + vimmer-ps to use purescript-language-server, however it crashes constantly with the following error:
```
Error: connect ECONNREFUSED ::1:15784
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 15784
}
```
Full error.log: [LanguageClient_stderr.log](https://github.com/nwolverson/purescript-language-server/files/7653871/LanguageClient_stderr.log)
purescript-language-server version: 0.16.1 from https://aur.archlinux.org/packages/purescript-language-server/
0.15.3 also doesn't work, but the error is slightly different:
```
/usr/lib/node_modules/purescript-language-server/server.js:2955
                  throw util.fromLeft(step);
                  ^

Error: connect ECONNREFUSED ::1:15651
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 15651
}

Node.js v17.2.0
```

The language server (configured by vimmer-ps) is started using the following command:
```
purescript-language-server --stdio --config '{"purescript":{"buildCommand":"spago build --purs-args --json-errors","addPscPackageSources":false,"pscIdePort":null,"autoStartPscIde":true,"pursExe":"purs","addNpmPath":true,"autocompleteAddImport":true,"addSpagoSources":true}}'
```
Which still results in ECONNREFUSED error.

Any ideas what's missing here?

Issue in language server repo: https://github.com/nwolverson/purescript-language-server/issues/167

**Comment by sriharshachilakapati** [comment]
It's weird that this is happening. vimmer-ps actually passes the `--stdio` flag and doesn't connect through TCP. I'm even more confused to see the compiled bundle of purescript-language-server in the error log.

What version of purescript-language-server are you currently using?

**Comment by sriharshachilakapati** [comment]
https://github.com/sriharshachilakapati/vimmer-ps/blob/master/plugin/vimmerps.vim#L38-L54

**Comment by wclr** [comment]
> What version of purescript-language-server are you currently using?

Purescript LS has migrated to esbuild bundle in the latest version. You may try the older versions just to check if it works.

**Comment by carbolymer** [comment]
0.16.1 from https://aur.archlinux.org/packages/purescript-language-server/
0.15.3 also doesn't work, but the error is slightly different:
```
/usr/lib/node_modules/purescript-language-server/server.js:2955
                  throw util.fromLeft(step);
                  ^

Error: connect ECONNREFUSED ::1:15651
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 15651
}

Node.js v17.2.0
```
EDIT: I've updated original post with purescript-language-server cmd arguments.
EDIT: Seems that purescript-language-server always tries to connect whenever I pass `--config`:
This command waits:
```
purescript-language-server  --stdio
```
This command fails with an error:
```
purescript-language-server --config '{"purescript":{}}' --stdio
```
EDIT: I've also tried to use `initializationOptions` instead, but language server still tries to connect:
```
diff --git a/plugin/vimmerps.vim b/plugin/vimmerps.vim
index 9972f45..458a8fa 100644
--- a/plugin/vimmerps.vim
+++ b/plugin/vimmerps.vim
@@ -38,11 +38,10 @@ if executable("purescript-language-server") || executable("npx")
     " Define the LanguageServer in the LanguageClient
     if executable("purescript-language-server")
         let g:LanguageClient_serverCommands.purescript =
-            \ [ 'purescript-language-server'
-            \ , '--stdio'
-            \ , '--config'
-            \ , json_encode(configWrapper)
-            \ ]
+            \ { 'name': 'purescript'
+            \ , 'command': ['purescript-language-server', '--stdio']
+            \ , 'initializationOptions': vimmerps_config
+            \ }
     else
         let g:LanguageClient_serverCommands.purescript =
             \ [ 'npx'

```

**Comment by carbolymer** [comment]
Issue was related to purescript-language-server and the fix is already released.

I think the usage of `--config` in vimmer-ps should be reconsidered, as suggested by language server author: https://github.com/nwolverson/purescript-language-server/issues/167#issuecomment-986284255
