### ISSUE TITLE
More Commands

### ISSUE THREAD

**Issue by mkohlhaas** [sriharshachilakapati/vimmer-ps#7]
Hi Shivam,

would it be possible to add more commands from the language server to your plugin? I'm especially thinking of the [casesplit-explicit](https://github.com/nwolverson/purescript-language-server#purescriptcasesplit-explicit) commands.

Thanks for this plugin!

**Comment by shivamashtikar** [comment]
Hi @mkohlhaas , yes it is possible to add it in the plugin 

But I'll not be able to do it right away as I've shifted to neovim LSP
It'll be greate If you want to give it a shot, here is the code to refer https://github.com/shivamashtikar/vimmer-ps/blob/526a77e2fb870816388455d95e1bb4ed9f5f2d3d/autoload/vimmerps.vim#L78 

Thanks :)
